// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helloworld.proto
// Protobuf C++ Version: 6.33.4

#ifndef helloworld_2eproto_2epb_2eh
#define helloworld_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_helloworld_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_helloworld_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_helloworld_2eproto;
}  // extern "C"
namespace helloworld {
enum CRPCProtocol_ErrorCode : int;
extern const uint32_t CRPCProtocol_ErrorCode_internal_data_[];
class A;
struct ADefaultTypeInternal;
extern ADefaultTypeInternal _A_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull A_class_data_;
class B;
struct BDefaultTypeInternal;
extern BDefaultTypeInternal _B_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull B_class_data_;
class CRPCProtocol;
struct CRPCProtocolDefaultTypeInternal;
extern CRPCProtocolDefaultTypeInternal _CRPCProtocol_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CRPCProtocol_class_data_;
class CRPCProtocol_Inner;
struct CRPCProtocol_InnerDefaultTypeInternal;
extern CRPCProtocol_InnerDefaultTypeInternal _CRPCProtocol_Inner_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CRPCProtocol_Inner_class_data_;
class HelloReply;
struct HelloReplyDefaultTypeInternal;
extern HelloReplyDefaultTypeInternal _HelloReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull HelloReply_class_data_;
class HelloRequest;
struct HelloRequestDefaultTypeInternal;
extern HelloRequestDefaultTypeInternal _HelloRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull HelloRequest_class_data_;
}  // namespace helloworld
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::helloworld::CRPCProtocol_ErrorCode_internal_data_>
    internal::EnumTraitsImpl::value<::helloworld::CRPCProtocol_ErrorCode>;
}  // namespace protobuf
}  // namespace google

namespace helloworld {
enum CRPCProtocol_ErrorCode : int {
  CRPCProtocol_ErrorCode_Unknown = 0,
  CRPCProtocol_ErrorCode_OK = 1,
  CRPCProtocol_ErrorCode_Fail = 2,
  CRPCProtocol_ErrorCode_NotInit = 3,
  CRPCProtocol_ErrorCode_NoResponse = 4,
  CRPCProtocol_ErrorCode_Unimplemented = 5,
  CRPCProtocol_ErrorCode_InvalidArgument = 6,
  CRPCProtocol_ErrorCode_CRPCProtocol_ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CRPCProtocol_ErrorCode_CRPCProtocol_ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CRPCProtocol_ErrorCode_internal_data_[];
inline constexpr CRPCProtocol_ErrorCode CRPCProtocol_ErrorCode_ErrorCode_MIN =
    static_cast<CRPCProtocol_ErrorCode>(0);
inline constexpr CRPCProtocol_ErrorCode CRPCProtocol_ErrorCode_ErrorCode_MAX =
    static_cast<CRPCProtocol_ErrorCode>(6);
inline bool CRPCProtocol_ErrorCode_IsValid(int value) {
  return 0 <= value && value <= 6;
}
inline constexpr int CRPCProtocol_ErrorCode_ErrorCode_ARRAYSIZE = 6 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CRPCProtocol_ErrorCode_descriptor();
template <typename T>
const ::std::string& CRPCProtocol_ErrorCode_Name(T value) {
  static_assert(::std::is_same<T, CRPCProtocol_ErrorCode>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ErrorCode_Name().");
  return CRPCProtocol_ErrorCode_Name(static_cast<CRPCProtocol_ErrorCode>(value));
}
template <>
inline const ::std::string& CRPCProtocol_ErrorCode_Name(CRPCProtocol_ErrorCode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CRPCProtocol_ErrorCode_descriptor, 0, 6>(
      static_cast<int>(value));
}
inline bool CRPCProtocol_ErrorCode_Parse(
    ::absl::string_view name, CRPCProtocol_ErrorCode* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CRPCProtocol_ErrorCode>(CRPCProtocol_ErrorCode_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class HelloRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:helloworld.HelloRequest) */ {
 public:
  inline HelloRequest() : HelloRequest(nullptr) {}
  ~HelloRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HelloRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HelloRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HelloRequest(::google::protobuf::internal::ConstantInitialized);

  inline HelloRequest(const HelloRequest& from) : HelloRequest(nullptr, from) {}
  inline HelloRequest(HelloRequest&& from) noexcept
      : HelloRequest(nullptr, ::std::move(from)) {}
  inline HelloRequest& operator=(const HelloRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HelloRequest& operator=(HelloRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HelloRequest& default_instance() {
    return *reinterpret_cast<const HelloRequest*>(
        &_HelloRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(HelloRequest& a, HelloRequest& b) { a.Swap(&b); }
  inline void Swap(HelloRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HelloRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HelloRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HelloRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HelloRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HelloRequest& from) { HelloRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HelloRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "helloworld.HelloRequest"; }

  explicit HelloRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HelloRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HelloRequest& from);
  HelloRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HelloRequest&& from) noexcept
      : HelloRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kAgeFieldNumber = 2,
  };
  // string name = 1;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // int32 age = 2;
  void clear_age() ;
  ::int32_t age() const;
  void set_age(::int32_t value);

  private:
  ::int32_t _internal_age() const;
  void _internal_set_age(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HelloRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::int32_t age_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HelloRequest_class_data_;
// -------------------------------------------------------------------

class HelloReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:helloworld.HelloReply) */ {
 public:
  inline HelloReply() : HelloReply(nullptr) {}
  ~HelloReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HelloReply* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HelloReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HelloReply(::google::protobuf::internal::ConstantInitialized);

  inline HelloReply(const HelloReply& from) : HelloReply(nullptr, from) {}
  inline HelloReply(HelloReply&& from) noexcept
      : HelloReply(nullptr, ::std::move(from)) {}
  inline HelloReply& operator=(const HelloReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline HelloReply& operator=(HelloReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HelloReply& default_instance() {
    return *reinterpret_cast<const HelloReply*>(
        &_HelloReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(HelloReply& a, HelloReply& b) { a.Swap(&b); }
  inline void Swap(HelloReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HelloReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HelloReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HelloReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HelloReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HelloReply& from) { HelloReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HelloReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "helloworld.HelloReply"; }

  explicit HelloReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HelloReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HelloReply& from);
  HelloReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HelloReply&& from) noexcept
      : HelloReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message() ;
  const ::std::string& message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_message();
  void set_allocated_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_message();

  public:
  // @@protoc_insertion_point(class_scope:helloworld.HelloReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 37,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HelloReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HelloReply_class_data_;
// -------------------------------------------------------------------

class CRPCProtocol_Inner final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:helloworld.CRPCProtocol.Inner) */ {
 public:
  inline CRPCProtocol_Inner() : CRPCProtocol_Inner(nullptr) {}
  ~CRPCProtocol_Inner() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CRPCProtocol_Inner* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CRPCProtocol_Inner));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CRPCProtocol_Inner(::google::protobuf::internal::ConstantInitialized);

  inline CRPCProtocol_Inner(const CRPCProtocol_Inner& from) : CRPCProtocol_Inner(nullptr, from) {}
  inline CRPCProtocol_Inner(CRPCProtocol_Inner&& from) noexcept
      : CRPCProtocol_Inner(nullptr, ::std::move(from)) {}
  inline CRPCProtocol_Inner& operator=(const CRPCProtocol_Inner& from) {
    CopyFrom(from);
    return *this;
  }
  inline CRPCProtocol_Inner& operator=(CRPCProtocol_Inner&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CRPCProtocol_Inner& default_instance() {
    return *reinterpret_cast<const CRPCProtocol_Inner*>(
        &_CRPCProtocol_Inner_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(CRPCProtocol_Inner& a, CRPCProtocol_Inner& b) { a.Swap(&b); }
  inline void Swap(CRPCProtocol_Inner* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CRPCProtocol_Inner* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CRPCProtocol_Inner* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CRPCProtocol_Inner>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CRPCProtocol_Inner& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CRPCProtocol_Inner& from) { CRPCProtocol_Inner::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CRPCProtocol_Inner* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "helloworld.CRPCProtocol.Inner"; }

  explicit CRPCProtocol_Inner(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CRPCProtocol_Inner(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CRPCProtocol_Inner& from);
  CRPCProtocol_Inner(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CRPCProtocol_Inner&& from) noexcept
      : CRPCProtocol_Inner(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMethodFieldNumber = 1,
    kCallbackFieldNumber = 2,
    kCallbackArgsFieldNumber = 3,
  };
  // string method = 1;
  void clear_method() ;
  const ::std::string& method() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_method(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_method();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_method();
  void set_allocated_method(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_method() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_method(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_method();

  public:
  // uint64 callback = 2;
  void clear_callback() ;
  ::uint64_t callback() const;
  void set_callback(::uint64_t value);

  private:
  ::uint64_t _internal_callback() const;
  void _internal_set_callback(::uint64_t value);

  public:
  // uint64 callbackArgs = 3;
  void clear_callbackargs() ;
  ::uint64_t callbackargs() const;
  void set_callbackargs(::uint64_t value);

  private:
  ::uint64_t _internal_callbackargs() const;
  void _internal_set_callbackargs(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:helloworld.CRPCProtocol.Inner)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 44,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CRPCProtocol_Inner& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr method_;
    ::uint64_t callback_;
    ::uint64_t callbackargs_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CRPCProtocol_Inner_class_data_;
// -------------------------------------------------------------------

class B final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:helloworld.B) */ {
 public:
  inline B() : B(nullptr) {}
  ~B() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(B* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(B));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR B(::google::protobuf::internal::ConstantInitialized);

  inline B(const B& from) : B(nullptr, from) {}
  inline B(B&& from) noexcept
      : B(nullptr, ::std::move(from)) {}
  inline B& operator=(const B& from) {
    CopyFrom(from);
    return *this;
  }
  inline B& operator=(B&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const B& default_instance() {
    return *reinterpret_cast<const B*>(
        &_B_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(B& a, B& b) { a.Swap(&b); }
  inline void Swap(B* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(B* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  B* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<B>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const B& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const B& from) { B::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(B* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "helloworld.B"; }

  explicit B(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  B(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const B& from);
  B(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, B&& from) noexcept
      : B(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBFieldNumber = 1,
  };
  // string b = 1;
  void clear_b() ;
  const ::std::string& b() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_b(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_b();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_b();
  void set_allocated_b(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_b() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_b(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_b();

  public:
  // @@protoc_insertion_point(class_scope:helloworld.B)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 22,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const B& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr b_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull B_class_data_;
// -------------------------------------------------------------------

class A final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:helloworld.A) */ {
 public:
  inline A() : A(nullptr) {}
  ~A() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(A* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(A));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR A(::google::protobuf::internal::ConstantInitialized);

  inline A(const A& from) : A(nullptr, from) {}
  inline A(A&& from) noexcept
      : A(nullptr, ::std::move(from)) {}
  inline A& operator=(const A& from) {
    CopyFrom(from);
    return *this;
  }
  inline A& operator=(A&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const A& default_instance() {
    return *reinterpret_cast<const A*>(
        &_A_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(A& a, A& b) { a.Swap(&b); }
  inline void Swap(A* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(A* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  A* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<A>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const A& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const A& from) { A::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(A* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "helloworld.A"; }

  explicit A(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  A(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const A& from);
  A(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, A&& from) noexcept
      : A(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAFieldNumber = 1,
  };
  // string a = 1;
  void clear_a() ;
  const ::std::string& a() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_a(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_a();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_a();
  void set_allocated_a(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_a() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_a(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_a();

  public:
  // @@protoc_insertion_point(class_scope:helloworld.A)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 22,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const A& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr a_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull A_class_data_;
// -------------------------------------------------------------------

class CRPCProtocol final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:helloworld.CRPCProtocol) */ {
 public:
  inline CRPCProtocol() : CRPCProtocol(nullptr) {}
  ~CRPCProtocol() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CRPCProtocol* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CRPCProtocol));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CRPCProtocol(::google::protobuf::internal::ConstantInitialized);

  inline CRPCProtocol(const CRPCProtocol& from) : CRPCProtocol(nullptr, from) {}
  inline CRPCProtocol(CRPCProtocol&& from) noexcept
      : CRPCProtocol(nullptr, ::std::move(from)) {}
  inline CRPCProtocol& operator=(const CRPCProtocol& from) {
    CopyFrom(from);
    return *this;
  }
  inline CRPCProtocol& operator=(CRPCProtocol&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CRPCProtocol& default_instance() {
    return *reinterpret_cast<const CRPCProtocol*>(
        &_CRPCProtocol_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(CRPCProtocol& a, CRPCProtocol& b) { a.Swap(&b); }
  inline void Swap(CRPCProtocol* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CRPCProtocol* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CRPCProtocol* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CRPCProtocol>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CRPCProtocol& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CRPCProtocol& from) { CRPCProtocol::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CRPCProtocol* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "helloworld.CRPCProtocol"; }

  explicit CRPCProtocol(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CRPCProtocol(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CRPCProtocol& from);
  CRPCProtocol(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CRPCProtocol&& from) noexcept
      : CRPCProtocol(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Inner = CRPCProtocol_Inner;
  using ErrorCode = CRPCProtocol_ErrorCode;
  static constexpr ErrorCode Unknown = CRPCProtocol_ErrorCode_Unknown;
  static constexpr ErrorCode OK = CRPCProtocol_ErrorCode_OK;
  static constexpr ErrorCode Fail = CRPCProtocol_ErrorCode_Fail;
  static constexpr ErrorCode NotInit = CRPCProtocol_ErrorCode_NotInit;
  static constexpr ErrorCode NoResponse = CRPCProtocol_ErrorCode_NoResponse;
  static constexpr ErrorCode Unimplemented = CRPCProtocol_ErrorCode_Unimplemented;
  static constexpr ErrorCode InvalidArgument = CRPCProtocol_ErrorCode_InvalidArgument;
  static inline bool ErrorCode_IsValid(int value) {
    return CRPCProtocol_ErrorCode_IsValid(value);
  }
  static constexpr ErrorCode ErrorCode_MIN = CRPCProtocol_ErrorCode_ErrorCode_MIN;
  static constexpr ErrorCode ErrorCode_MAX = CRPCProtocol_ErrorCode_ErrorCode_MAX;
  static constexpr int ErrorCode_ARRAYSIZE = CRPCProtocol_ErrorCode_ErrorCode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ErrorCode_descriptor() {
    return CRPCProtocol_ErrorCode_descriptor();
  }
  template <typename T>
  static inline const ::std::string& ErrorCode_Name(T value) {
    return CRPCProtocol_ErrorCode_Name(value);
  }
  static inline bool ErrorCode_Parse(
      ::absl::string_view name, ErrorCode* PROTOBUF_NONNULL value) {
    return CRPCProtocol_ErrorCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kMethodFieldNumber = 1,
    kRequestFieldNumber = 3,
    kResponseFieldNumber = 4,
    kMsgFieldNumber = 11,
    kInnerFieldNumber = 100,
    kFunHandleFieldNumber = 2,
    kCodeFieldNumber = 10,
  };
  // string method = 1;
  void clear_method() ;
  const ::std::string& method() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_method(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_method();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_method();
  void set_allocated_method(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_method() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_method(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_method();

  public:
  // bytes request = 3;
  void clear_request() ;
  const ::std::string& request() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_request(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_request();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_request();
  void set_allocated_request(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_request() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_request(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_request();

  public:
  // bytes response = 4;
  void clear_response() ;
  const ::std::string& response() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_response(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_response();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_response();
  void set_allocated_response(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_response() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_response(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_response();

  public:
  // string msg = 11;
  void clear_msg() ;
  const ::std::string& msg() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_msg(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_msg();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_msg();
  void set_allocated_msg(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_msg() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_msg();

  public:
  // .helloworld.CRPCProtocol.Inner inner = 100;
  bool has_inner() const;
  void clear_inner() ;
  const ::helloworld::CRPCProtocol_Inner& inner() const;
  [[nodiscard]] ::helloworld::CRPCProtocol_Inner* PROTOBUF_NULLABLE release_inner();
  ::helloworld::CRPCProtocol_Inner* PROTOBUF_NONNULL mutable_inner();
  void set_allocated_inner(::helloworld::CRPCProtocol_Inner* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_inner(::helloworld::CRPCProtocol_Inner* PROTOBUF_NULLABLE value);
  ::helloworld::CRPCProtocol_Inner* PROTOBUF_NULLABLE unsafe_arena_release_inner();

  private:
  const ::helloworld::CRPCProtocol_Inner& _internal_inner() const;
  ::helloworld::CRPCProtocol_Inner* PROTOBUF_NONNULL _internal_mutable_inner();

  public:
  // uint64 funHandle = 2;
  void clear_funhandle() ;
  ::uint64_t funhandle() const;
  void set_funhandle(::uint64_t value);

  private:
  ::uint64_t _internal_funhandle() const;
  void _internal_set_funhandle(::uint64_t value);

  public:
  // .helloworld.CRPCProtocol.ErrorCode code = 10;
  void clear_code() ;
  ::helloworld::CRPCProtocol_ErrorCode code() const;
  void set_code(::helloworld::CRPCProtocol_ErrorCode value);

  private:
  ::helloworld::CRPCProtocol_ErrorCode _internal_code() const;
  void _internal_set_code(::helloworld::CRPCProtocol_ErrorCode value);

  public:
  // @@protoc_insertion_point(class_scope:helloworld.CRPCProtocol)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 7,
                                   1, 41,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CRPCProtocol& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr method_;
    ::google::protobuf::internal::ArenaStringPtr request_;
    ::google::protobuf::internal::ArenaStringPtr response_;
    ::google::protobuf::internal::ArenaStringPtr msg_;
    ::helloworld::CRPCProtocol_Inner* PROTOBUF_NULLABLE inner_;
    ::uint64_t funhandle_;
    int code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CRPCProtocol_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// HelloRequest

// string name = 1;
inline void HelloRequest::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& HelloRequest::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.HelloRequest.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HelloRequest::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:helloworld.HelloRequest.name)
}
inline ::std::string* PROTOBUF_NONNULL HelloRequest::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:helloworld.HelloRequest.name)
  return _s;
}
inline const ::std::string& HelloRequest::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void HelloRequest::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HelloRequest::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HelloRequest::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.HelloRequest.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void HelloRequest::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:helloworld.HelloRequest.name)
}

// int32 age = 2;
inline void HelloRequest::clear_age() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.age_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t HelloRequest::age() const {
  // @@protoc_insertion_point(field_get:helloworld.HelloRequest.age)
  return _internal_age();
}
inline void HelloRequest::set_age(::int32_t value) {
  _internal_set_age(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:helloworld.HelloRequest.age)
}
inline ::int32_t HelloRequest::_internal_age() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.age_;
}
inline void HelloRequest::_internal_set_age(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.age_ = value;
}

// -------------------------------------------------------------------

// HelloReply

// string message = 1;
inline void HelloReply::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& HelloReply::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.HelloReply.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HelloReply::set_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:helloworld.HelloReply.message)
}
inline ::std::string* PROTOBUF_NONNULL HelloReply::mutable_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:helloworld.HelloReply.message)
  return _s;
}
inline const ::std::string& HelloReply::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void HelloReply::_internal_set_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HelloReply::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HelloReply::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.HelloReply.message)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void HelloReply::set_allocated_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:helloworld.HelloReply.message)
}

// -------------------------------------------------------------------

// A

// string a = 1;
inline void A::clear_a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.a_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& A::a() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.A.a)
  return _internal_a();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void A::set_a(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.a_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:helloworld.A.a)
}
inline ::std::string* PROTOBUF_NONNULL A::mutable_a()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_a();
  // @@protoc_insertion_point(field_mutable:helloworld.A.a)
  return _s;
}
inline const ::std::string& A::_internal_a() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.a_.Get();
}
inline void A::_internal_set_a(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.a_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL A::_internal_mutable_a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.a_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE A::release_a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.A.a)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.a_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.a_.Set("", GetArena());
  }
  return released;
}
inline void A::set_allocated_a(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.a_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.a_.IsDefault()) {
    _impl_.a_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:helloworld.A.a)
}

// -------------------------------------------------------------------

// B

// string b = 1;
inline void B::clear_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& B::b() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.B.b)
  return _internal_b();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void B::set_b(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.b_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:helloworld.B.b)
}
inline ::std::string* PROTOBUF_NONNULL B::mutable_b()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_b();
  // @@protoc_insertion_point(field_mutable:helloworld.B.b)
  return _s;
}
inline const ::std::string& B::_internal_b() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.b_.Get();
}
inline void B::_internal_set_b(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL B::_internal_mutable_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.b_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE B::release_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.B.b)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.b_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.b_.Set("", GetArena());
  }
  return released;
}
inline void B::set_allocated_b(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.b_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.b_.IsDefault()) {
    _impl_.b_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:helloworld.B.b)
}

// -------------------------------------------------------------------

// CRPCProtocol_Inner

// string method = 1;
inline void CRPCProtocol_Inner::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CRPCProtocol_Inner::method() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.Inner.method)
  return _internal_method();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CRPCProtocol_Inner::set_method(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.method_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.Inner.method)
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol_Inner::mutable_method()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_method();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.Inner.method)
  return _s;
}
inline const ::std::string& CRPCProtocol_Inner::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.method_.Get();
}
inline void CRPCProtocol_Inner::_internal_set_method(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol_Inner::_internal_mutable_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.method_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CRPCProtocol_Inner::release_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.Inner.method)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.method_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.method_.Set("", GetArena());
  }
  return released;
}
inline void CRPCProtocol_Inner::set_allocated_method(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.method_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.method_.IsDefault()) {
    _impl_.method_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.Inner.method)
}

// uint64 callback = 2;
inline void CRPCProtocol_Inner::clear_callback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.callback_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t CRPCProtocol_Inner::callback() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.Inner.callback)
  return _internal_callback();
}
inline void CRPCProtocol_Inner::set_callback(::uint64_t value) {
  _internal_set_callback(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.Inner.callback)
}
inline ::uint64_t CRPCProtocol_Inner::_internal_callback() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.callback_;
}
inline void CRPCProtocol_Inner::_internal_set_callback(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.callback_ = value;
}

// uint64 callbackArgs = 3;
inline void CRPCProtocol_Inner::clear_callbackargs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.callbackargs_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t CRPCProtocol_Inner::callbackargs() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.Inner.callbackArgs)
  return _internal_callbackargs();
}
inline void CRPCProtocol_Inner::set_callbackargs(::uint64_t value) {
  _internal_set_callbackargs(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.Inner.callbackArgs)
}
inline ::uint64_t CRPCProtocol_Inner::_internal_callbackargs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.callbackargs_;
}
inline void CRPCProtocol_Inner::_internal_set_callbackargs(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.callbackargs_ = value;
}

// -------------------------------------------------------------------

// CRPCProtocol

// string method = 1;
inline void CRPCProtocol::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CRPCProtocol::method() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.method)
  return _internal_method();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CRPCProtocol::set_method(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.method_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.method)
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol::mutable_method()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_method();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.method)
  return _s;
}
inline const ::std::string& CRPCProtocol::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.method_.Get();
}
inline void CRPCProtocol::_internal_set_method(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol::_internal_mutable_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.method_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CRPCProtocol::release_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.method)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.method_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.method_.Set("", GetArena());
  }
  return released;
}
inline void CRPCProtocol::set_allocated_method(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.method_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.method_.IsDefault()) {
    _impl_.method_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.method)
}

// uint64 funHandle = 2;
inline void CRPCProtocol::clear_funhandle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.funhandle_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint64_t CRPCProtocol::funhandle() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.funHandle)
  return _internal_funhandle();
}
inline void CRPCProtocol::set_funhandle(::uint64_t value) {
  _internal_set_funhandle(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.funHandle)
}
inline ::uint64_t CRPCProtocol::_internal_funhandle() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.funhandle_;
}
inline void CRPCProtocol::_internal_set_funhandle(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.funhandle_ = value;
}

// bytes request = 3;
inline void CRPCProtocol::clear_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& CRPCProtocol::request() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.request)
  return _internal_request();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CRPCProtocol::set_request(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.request_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.request)
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol::mutable_request()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_request();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.request)
  return _s;
}
inline const ::std::string& CRPCProtocol::_internal_request() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.request_.Get();
}
inline void CRPCProtocol::_internal_set_request(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol::_internal_mutable_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.request_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CRPCProtocol::release_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.request)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.request_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.request_.Set("", GetArena());
  }
  return released;
}
inline void CRPCProtocol::set_allocated_request(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.request_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.request_.IsDefault()) {
    _impl_.request_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.request)
}

// bytes response = 4;
inline void CRPCProtocol::clear_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.response_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& CRPCProtocol::response() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.response)
  return _internal_response();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CRPCProtocol::set_response(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.response_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.response)
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol::mutable_response()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_response();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.response)
  return _s;
}
inline const ::std::string& CRPCProtocol::_internal_response() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.response_.Get();
}
inline void CRPCProtocol::_internal_set_response(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.response_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol::_internal_mutable_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.response_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CRPCProtocol::release_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.response)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.response_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.response_.Set("", GetArena());
  }
  return released;
}
inline void CRPCProtocol::set_allocated_response(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.response_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.response_.IsDefault()) {
    _impl_.response_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.response)
}

// .helloworld.CRPCProtocol.ErrorCode code = 10;
inline void CRPCProtocol::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::helloworld::CRPCProtocol_ErrorCode CRPCProtocol::code() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.code)
  return _internal_code();
}
inline void CRPCProtocol::set_code(::helloworld::CRPCProtocol_ErrorCode value) {
  _internal_set_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.code)
}
inline ::helloworld::CRPCProtocol_ErrorCode CRPCProtocol::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::helloworld::CRPCProtocol_ErrorCode>(_impl_.code_);
}
inline void CRPCProtocol::_internal_set_code(::helloworld::CRPCProtocol_ErrorCode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = value;
}

// string msg = 11;
inline void CRPCProtocol::clear_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& CRPCProtocol::msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.msg)
  return _internal_msg();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CRPCProtocol::set_msg(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.msg)
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol::mutable_msg()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.msg)
  return _s;
}
inline const ::std::string& CRPCProtocol::_internal_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_.Get();
}
inline void CRPCProtocol::_internal_set_msg(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CRPCProtocol::_internal_mutable_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.msg_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CRPCProtocol::release_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.msg)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.msg_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.msg_.Set("", GetArena());
  }
  return released;
}
inline void CRPCProtocol::set_allocated_msg(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.msg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.msg)
}

// .helloworld.CRPCProtocol.Inner inner = 100;
inline bool CRPCProtocol::has_inner() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.inner_ != nullptr);
  return value;
}
inline void CRPCProtocol::clear_inner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.inner_ != nullptr) _impl_.inner_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::helloworld::CRPCProtocol_Inner& CRPCProtocol::_internal_inner() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::helloworld::CRPCProtocol_Inner* p = _impl_.inner_;
  return p != nullptr ? *p : reinterpret_cast<const ::helloworld::CRPCProtocol_Inner&>(::helloworld::_CRPCProtocol_Inner_default_instance_);
}
inline const ::helloworld::CRPCProtocol_Inner& CRPCProtocol::inner() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.inner)
  return _internal_inner();
}
inline void CRPCProtocol::unsafe_arena_set_allocated_inner(
    ::helloworld::CRPCProtocol_Inner* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.inner_);
  }
  _impl_.inner_ = reinterpret_cast<::helloworld::CRPCProtocol_Inner*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helloworld.CRPCProtocol.inner)
}
inline ::helloworld::CRPCProtocol_Inner* PROTOBUF_NULLABLE CRPCProtocol::release_inner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::helloworld::CRPCProtocol_Inner* released = _impl_.inner_;
  _impl_.inner_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::helloworld::CRPCProtocol_Inner* PROTOBUF_NULLABLE CRPCProtocol::unsafe_arena_release_inner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.inner)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::helloworld::CRPCProtocol_Inner* temp = _impl_.inner_;
  _impl_.inner_ = nullptr;
  return temp;
}
inline ::helloworld::CRPCProtocol_Inner* PROTOBUF_NONNULL CRPCProtocol::_internal_mutable_inner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.inner_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::helloworld::CRPCProtocol_Inner>(GetArena());
    _impl_.inner_ = reinterpret_cast<::helloworld::CRPCProtocol_Inner*>(p);
  }
  return _impl_.inner_;
}
inline ::helloworld::CRPCProtocol_Inner* PROTOBUF_NONNULL CRPCProtocol::mutable_inner()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::helloworld::CRPCProtocol_Inner* _msg = _internal_mutable_inner();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.inner)
  return _msg;
}
inline void CRPCProtocol::set_allocated_inner(::helloworld::CRPCProtocol_Inner* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.inner_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.inner_ = reinterpret_cast<::helloworld::CRPCProtocol_Inner*>(value);
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.inner)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace helloworld


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::helloworld::CRPCProtocol_ErrorCode> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::helloworld::CRPCProtocol_ErrorCode>() {
  return ::helloworld::CRPCProtocol_ErrorCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // helloworld_2eproto_2epb_2eh
