// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_helloworld_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_helloworld_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_helloworld_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_helloworld_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_helloworld_2eproto;
namespace helloworld {
class A;
struct ADefaultTypeInternal;
extern ADefaultTypeInternal _A_default_instance_;
class B;
struct BDefaultTypeInternal;
extern BDefaultTypeInternal _B_default_instance_;
class CRPCProtocol;
struct CRPCProtocolDefaultTypeInternal;
extern CRPCProtocolDefaultTypeInternal _CRPCProtocol_default_instance_;
class CRPCProtocol_Inner;
struct CRPCProtocol_InnerDefaultTypeInternal;
extern CRPCProtocol_InnerDefaultTypeInternal _CRPCProtocol_Inner_default_instance_;
class HelloReply;
struct HelloReplyDefaultTypeInternal;
extern HelloReplyDefaultTypeInternal _HelloReply_default_instance_;
class HelloRequest;
struct HelloRequestDefaultTypeInternal;
extern HelloRequestDefaultTypeInternal _HelloRequest_default_instance_;
}  // namespace helloworld
PROTOBUF_NAMESPACE_OPEN
template<> ::helloworld::A* Arena::CreateMaybeMessage<::helloworld::A>(Arena*);
template<> ::helloworld::B* Arena::CreateMaybeMessage<::helloworld::B>(Arena*);
template<> ::helloworld::CRPCProtocol* Arena::CreateMaybeMessage<::helloworld::CRPCProtocol>(Arena*);
template<> ::helloworld::CRPCProtocol_Inner* Arena::CreateMaybeMessage<::helloworld::CRPCProtocol_Inner>(Arena*);
template<> ::helloworld::HelloReply* Arena::CreateMaybeMessage<::helloworld::HelloReply>(Arena*);
template<> ::helloworld::HelloRequest* Arena::CreateMaybeMessage<::helloworld::HelloRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace helloworld {

enum CRPCProtocol_ErrorCode : int {
  CRPCProtocol_ErrorCode_Unknown = 0,
  CRPCProtocol_ErrorCode_OK = 1,
  CRPCProtocol_ErrorCode_Fail = 2,
  CRPCProtocol_ErrorCode_NotInit = 3,
  CRPCProtocol_ErrorCode_NoResponse = 4,
  CRPCProtocol_ErrorCode_Unimplemented = 5,
  CRPCProtocol_ErrorCode_InvalidArgument = 6,
  CRPCProtocol_ErrorCode_CRPCProtocol_ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CRPCProtocol_ErrorCode_CRPCProtocol_ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CRPCProtocol_ErrorCode_IsValid(int value);
constexpr CRPCProtocol_ErrorCode CRPCProtocol_ErrorCode_ErrorCode_MIN = CRPCProtocol_ErrorCode_Unknown;
constexpr CRPCProtocol_ErrorCode CRPCProtocol_ErrorCode_ErrorCode_MAX = CRPCProtocol_ErrorCode_InvalidArgument;
constexpr int CRPCProtocol_ErrorCode_ErrorCode_ARRAYSIZE = CRPCProtocol_ErrorCode_ErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CRPCProtocol_ErrorCode_descriptor();
template<typename T>
inline const std::string& CRPCProtocol_ErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CRPCProtocol_ErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CRPCProtocol_ErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CRPCProtocol_ErrorCode_descriptor(), enum_t_value);
}
inline bool CRPCProtocol_ErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CRPCProtocol_ErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CRPCProtocol_ErrorCode>(
    CRPCProtocol_ErrorCode_descriptor(), name, value);
}
// ===================================================================

class HelloRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helloworld.HelloRequest) */ {
 public:
  inline HelloRequest() : HelloRequest(nullptr) {}
  ~HelloRequest() override;
  explicit PROTOBUF_CONSTEXPR HelloRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HelloRequest(const HelloRequest& from);
  HelloRequest(HelloRequest&& from) noexcept
    : HelloRequest() {
    *this = ::std::move(from);
  }

  inline HelloRequest& operator=(const HelloRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HelloRequest& operator=(HelloRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HelloRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HelloRequest* internal_default_instance() {
    return reinterpret_cast<const HelloRequest*>(
               &_HelloRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HelloRequest& a, HelloRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HelloRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HelloRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HelloRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HelloRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HelloRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HelloRequest& from) {
    HelloRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helloworld.HelloRequest";
  }
  protected:
  explicit HelloRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kAgeFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 age = 2;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t age_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};
// -------------------------------------------------------------------

class HelloReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helloworld.HelloReply) */ {
 public:
  inline HelloReply() : HelloReply(nullptr) {}
  ~HelloReply() override;
  explicit PROTOBUF_CONSTEXPR HelloReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HelloReply(const HelloReply& from);
  HelloReply(HelloReply&& from) noexcept
    : HelloReply() {
    *this = ::std::move(from);
  }

  inline HelloReply& operator=(const HelloReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline HelloReply& operator=(HelloReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HelloReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const HelloReply* internal_default_instance() {
    return reinterpret_cast<const HelloReply*>(
               &_HelloReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HelloReply& a, HelloReply& b) {
    a.Swap(&b);
  }
  inline void Swap(HelloReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HelloReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HelloReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HelloReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HelloReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HelloReply& from) {
    HelloReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helloworld.HelloReply";
  }
  protected:
  explicit HelloReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:helloworld.HelloReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};
// -------------------------------------------------------------------

class A final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helloworld.A) */ {
 public:
  inline A() : A(nullptr) {}
  ~A() override;
  explicit PROTOBUF_CONSTEXPR A(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  A(const A& from);
  A(A&& from) noexcept
    : A() {
    *this = ::std::move(from);
  }

  inline A& operator=(const A& from) {
    CopyFrom(from);
    return *this;
  }
  inline A& operator=(A&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const A& default_instance() {
    return *internal_default_instance();
  }
  static inline const A* internal_default_instance() {
    return reinterpret_cast<const A*>(
               &_A_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(A& a, A& b) {
    a.Swap(&b);
  }
  inline void Swap(A* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(A* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  A* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<A>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const A& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const A& from) {
    A::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(A* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helloworld.A";
  }
  protected:
  explicit A(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAFieldNumber = 1,
  };
  // string a = 1;
  void clear_a();
  const std::string& a() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_a(ArgT0&& arg0, ArgT... args);
  std::string* mutable_a();
  PROTOBUF_NODISCARD std::string* release_a();
  void set_allocated_a(std::string* a);
  private:
  const std::string& _internal_a() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_a(const std::string& value);
  std::string* _internal_mutable_a();
  public:

  // @@protoc_insertion_point(class_scope:helloworld.A)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr a_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};
// -------------------------------------------------------------------

class B final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helloworld.B) */ {
 public:
  inline B() : B(nullptr) {}
  ~B() override;
  explicit PROTOBUF_CONSTEXPR B(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  B(const B& from);
  B(B&& from) noexcept
    : B() {
    *this = ::std::move(from);
  }

  inline B& operator=(const B& from) {
    CopyFrom(from);
    return *this;
  }
  inline B& operator=(B&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const B& default_instance() {
    return *internal_default_instance();
  }
  static inline const B* internal_default_instance() {
    return reinterpret_cast<const B*>(
               &_B_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(B& a, B& b) {
    a.Swap(&b);
  }
  inline void Swap(B* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(B* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  B* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<B>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const B& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const B& from) {
    B::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(B* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helloworld.B";
  }
  protected:
  explicit B(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBFieldNumber = 1,
  };
  // string b = 1;
  void clear_b();
  const std::string& b() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_b(ArgT0&& arg0, ArgT... args);
  std::string* mutable_b();
  PROTOBUF_NODISCARD std::string* release_b();
  void set_allocated_b(std::string* b);
  private:
  const std::string& _internal_b() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_b(const std::string& value);
  std::string* _internal_mutable_b();
  public:

  // @@protoc_insertion_point(class_scope:helloworld.B)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr b_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};
// -------------------------------------------------------------------

class CRPCProtocol_Inner final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helloworld.CRPCProtocol.Inner) */ {
 public:
  inline CRPCProtocol_Inner() : CRPCProtocol_Inner(nullptr) {}
  ~CRPCProtocol_Inner() override;
  explicit PROTOBUF_CONSTEXPR CRPCProtocol_Inner(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CRPCProtocol_Inner(const CRPCProtocol_Inner& from);
  CRPCProtocol_Inner(CRPCProtocol_Inner&& from) noexcept
    : CRPCProtocol_Inner() {
    *this = ::std::move(from);
  }

  inline CRPCProtocol_Inner& operator=(const CRPCProtocol_Inner& from) {
    CopyFrom(from);
    return *this;
  }
  inline CRPCProtocol_Inner& operator=(CRPCProtocol_Inner&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CRPCProtocol_Inner& default_instance() {
    return *internal_default_instance();
  }
  static inline const CRPCProtocol_Inner* internal_default_instance() {
    return reinterpret_cast<const CRPCProtocol_Inner*>(
               &_CRPCProtocol_Inner_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(CRPCProtocol_Inner& a, CRPCProtocol_Inner& b) {
    a.Swap(&b);
  }
  inline void Swap(CRPCProtocol_Inner* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CRPCProtocol_Inner* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CRPCProtocol_Inner* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CRPCProtocol_Inner>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CRPCProtocol_Inner& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CRPCProtocol_Inner& from) {
    CRPCProtocol_Inner::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CRPCProtocol_Inner* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helloworld.CRPCProtocol.Inner";
  }
  protected:
  explicit CRPCProtocol_Inner(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMethodFieldNumber = 1,
    kCallbackFieldNumber = 2,
    kCallbackArgsFieldNumber = 3,
  };
  // string method = 1;
  void clear_method();
  const std::string& method() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_method(ArgT0&& arg0, ArgT... args);
  std::string* mutable_method();
  PROTOBUF_NODISCARD std::string* release_method();
  void set_allocated_method(std::string* method);
  private:
  const std::string& _internal_method() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_method(const std::string& value);
  std::string* _internal_mutable_method();
  public:

  // uint64 callback = 2;
  void clear_callback();
  uint64_t callback() const;
  void set_callback(uint64_t value);
  private:
  uint64_t _internal_callback() const;
  void _internal_set_callback(uint64_t value);
  public:

  // uint64 callbackArgs = 3;
  void clear_callbackargs();
  uint64_t callbackargs() const;
  void set_callbackargs(uint64_t value);
  private:
  uint64_t _internal_callbackargs() const;
  void _internal_set_callbackargs(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:helloworld.CRPCProtocol.Inner)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_;
    uint64_t callback_;
    uint64_t callbackargs_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};
// -------------------------------------------------------------------

class CRPCProtocol final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helloworld.CRPCProtocol) */ {
 public:
  inline CRPCProtocol() : CRPCProtocol(nullptr) {}
  ~CRPCProtocol() override;
  explicit PROTOBUF_CONSTEXPR CRPCProtocol(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CRPCProtocol(const CRPCProtocol& from);
  CRPCProtocol(CRPCProtocol&& from) noexcept
    : CRPCProtocol() {
    *this = ::std::move(from);
  }

  inline CRPCProtocol& operator=(const CRPCProtocol& from) {
    CopyFrom(from);
    return *this;
  }
  inline CRPCProtocol& operator=(CRPCProtocol&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CRPCProtocol& default_instance() {
    return *internal_default_instance();
  }
  static inline const CRPCProtocol* internal_default_instance() {
    return reinterpret_cast<const CRPCProtocol*>(
               &_CRPCProtocol_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(CRPCProtocol& a, CRPCProtocol& b) {
    a.Swap(&b);
  }
  inline void Swap(CRPCProtocol* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CRPCProtocol* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CRPCProtocol* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CRPCProtocol>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CRPCProtocol& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CRPCProtocol& from) {
    CRPCProtocol::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CRPCProtocol* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helloworld.CRPCProtocol";
  }
  protected:
  explicit CRPCProtocol(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CRPCProtocol_Inner Inner;

  typedef CRPCProtocol_ErrorCode ErrorCode;
  static constexpr ErrorCode Unknown =
    CRPCProtocol_ErrorCode_Unknown;
  static constexpr ErrorCode OK =
    CRPCProtocol_ErrorCode_OK;
  static constexpr ErrorCode Fail =
    CRPCProtocol_ErrorCode_Fail;
  static constexpr ErrorCode NotInit =
    CRPCProtocol_ErrorCode_NotInit;
  static constexpr ErrorCode NoResponse =
    CRPCProtocol_ErrorCode_NoResponse;
  static constexpr ErrorCode Unimplemented =
    CRPCProtocol_ErrorCode_Unimplemented;
  static constexpr ErrorCode InvalidArgument =
    CRPCProtocol_ErrorCode_InvalidArgument;
  static inline bool ErrorCode_IsValid(int value) {
    return CRPCProtocol_ErrorCode_IsValid(value);
  }
  static constexpr ErrorCode ErrorCode_MIN =
    CRPCProtocol_ErrorCode_ErrorCode_MIN;
  static constexpr ErrorCode ErrorCode_MAX =
    CRPCProtocol_ErrorCode_ErrorCode_MAX;
  static constexpr int ErrorCode_ARRAYSIZE =
    CRPCProtocol_ErrorCode_ErrorCode_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ErrorCode_descriptor() {
    return CRPCProtocol_ErrorCode_descriptor();
  }
  template<typename T>
  static inline const std::string& ErrorCode_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ErrorCode>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ErrorCode_Name.");
    return CRPCProtocol_ErrorCode_Name(enum_t_value);
  }
  static inline bool ErrorCode_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ErrorCode* value) {
    return CRPCProtocol_ErrorCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMethodFieldNumber = 1,
    kRequestFieldNumber = 3,
    kResponseFieldNumber = 4,
    kMsgFieldNumber = 11,
    kInnerFieldNumber = 100,
    kFunHandleFieldNumber = 2,
    kCodeFieldNumber = 10,
  };
  // string method = 1;
  void clear_method();
  const std::string& method() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_method(ArgT0&& arg0, ArgT... args);
  std::string* mutable_method();
  PROTOBUF_NODISCARD std::string* release_method();
  void set_allocated_method(std::string* method);
  private:
  const std::string& _internal_method() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_method(const std::string& value);
  std::string* _internal_mutable_method();
  public:

  // bytes request = 3;
  void clear_request();
  const std::string& request() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_request(ArgT0&& arg0, ArgT... args);
  std::string* mutable_request();
  PROTOBUF_NODISCARD std::string* release_request();
  void set_allocated_request(std::string* request);
  private:
  const std::string& _internal_request() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request(const std::string& value);
  std::string* _internal_mutable_request();
  public:

  // bytes response = 4;
  void clear_response();
  const std::string& response() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_response(ArgT0&& arg0, ArgT... args);
  std::string* mutable_response();
  PROTOBUF_NODISCARD std::string* release_response();
  void set_allocated_response(std::string* response);
  private:
  const std::string& _internal_response() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_response(const std::string& value);
  std::string* _internal_mutable_response();
  public:

  // string msg = 11;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // .helloworld.CRPCProtocol.Inner inner = 100;
  bool has_inner() const;
  private:
  bool _internal_has_inner() const;
  public:
  void clear_inner();
  const ::helloworld::CRPCProtocol_Inner& inner() const;
  PROTOBUF_NODISCARD ::helloworld::CRPCProtocol_Inner* release_inner();
  ::helloworld::CRPCProtocol_Inner* mutable_inner();
  void set_allocated_inner(::helloworld::CRPCProtocol_Inner* inner);
  private:
  const ::helloworld::CRPCProtocol_Inner& _internal_inner() const;
  ::helloworld::CRPCProtocol_Inner* _internal_mutable_inner();
  public:
  void unsafe_arena_set_allocated_inner(
      ::helloworld::CRPCProtocol_Inner* inner);
  ::helloworld::CRPCProtocol_Inner* unsafe_arena_release_inner();

  // uint64 funHandle = 2;
  void clear_funhandle();
  uint64_t funhandle() const;
  void set_funhandle(uint64_t value);
  private:
  uint64_t _internal_funhandle() const;
  void _internal_set_funhandle(uint64_t value);
  public:

  // .helloworld.CRPCProtocol.ErrorCode code = 10;
  void clear_code();
  ::helloworld::CRPCProtocol_ErrorCode code() const;
  void set_code(::helloworld::CRPCProtocol_ErrorCode value);
  private:
  ::helloworld::CRPCProtocol_ErrorCode _internal_code() const;
  void _internal_set_code(::helloworld::CRPCProtocol_ErrorCode value);
  public:

  // @@protoc_insertion_point(class_scope:helloworld.CRPCProtocol)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr response_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    ::helloworld::CRPCProtocol_Inner* inner_;
    uint64_t funhandle_;
    int code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_helloworld_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HelloRequest

// string name = 1;
inline void HelloRequest::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& HelloRequest::name() const {
  // @@protoc_insertion_point(field_get:helloworld.HelloRequest.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HelloRequest::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:helloworld.HelloRequest.name)
}
inline std::string* HelloRequest::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:helloworld.HelloRequest.name)
  return _s;
}
inline const std::string& HelloRequest::_internal_name() const {
  return _impl_.name_.Get();
}
inline void HelloRequest::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* HelloRequest::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* HelloRequest::release_name() {
  // @@protoc_insertion_point(field_release:helloworld.HelloRequest.name)
  return _impl_.name_.Release();
}
inline void HelloRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:helloworld.HelloRequest.name)
}

// int32 age = 2;
inline void HelloRequest::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t HelloRequest::_internal_age() const {
  return _impl_.age_;
}
inline int32_t HelloRequest::age() const {
  // @@protoc_insertion_point(field_get:helloworld.HelloRequest.age)
  return _internal_age();
}
inline void HelloRequest::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void HelloRequest::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:helloworld.HelloRequest.age)
}

// -------------------------------------------------------------------

// HelloReply

// string message = 1;
inline void HelloReply::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& HelloReply::message() const {
  // @@protoc_insertion_point(field_get:helloworld.HelloReply.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HelloReply::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:helloworld.HelloReply.message)
}
inline std::string* HelloReply::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:helloworld.HelloReply.message)
  return _s;
}
inline const std::string& HelloReply::_internal_message() const {
  return _impl_.message_.Get();
}
inline void HelloReply::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* HelloReply::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* HelloReply::release_message() {
  // @@protoc_insertion_point(field_release:helloworld.HelloReply.message)
  return _impl_.message_.Release();
}
inline void HelloReply::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:helloworld.HelloReply.message)
}

// -------------------------------------------------------------------

// A

// string a = 1;
inline void A::clear_a() {
  _impl_.a_.ClearToEmpty();
}
inline const std::string& A::a() const {
  // @@protoc_insertion_point(field_get:helloworld.A.a)
  return _internal_a();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void A::set_a(ArgT0&& arg0, ArgT... args) {
 
 _impl_.a_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:helloworld.A.a)
}
inline std::string* A::mutable_a() {
  std::string* _s = _internal_mutable_a();
  // @@protoc_insertion_point(field_mutable:helloworld.A.a)
  return _s;
}
inline const std::string& A::_internal_a() const {
  return _impl_.a_.Get();
}
inline void A::_internal_set_a(const std::string& value) {
  
  _impl_.a_.Set(value, GetArenaForAllocation());
}
inline std::string* A::_internal_mutable_a() {
  
  return _impl_.a_.Mutable(GetArenaForAllocation());
}
inline std::string* A::release_a() {
  // @@protoc_insertion_point(field_release:helloworld.A.a)
  return _impl_.a_.Release();
}
inline void A::set_allocated_a(std::string* a) {
  if (a != nullptr) {
    
  } else {
    
  }
  _impl_.a_.SetAllocated(a, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.a_.IsDefault()) {
    _impl_.a_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:helloworld.A.a)
}

// -------------------------------------------------------------------

// B

// string b = 1;
inline void B::clear_b() {
  _impl_.b_.ClearToEmpty();
}
inline const std::string& B::b() const {
  // @@protoc_insertion_point(field_get:helloworld.B.b)
  return _internal_b();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void B::set_b(ArgT0&& arg0, ArgT... args) {
 
 _impl_.b_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:helloworld.B.b)
}
inline std::string* B::mutable_b() {
  std::string* _s = _internal_mutable_b();
  // @@protoc_insertion_point(field_mutable:helloworld.B.b)
  return _s;
}
inline const std::string& B::_internal_b() const {
  return _impl_.b_.Get();
}
inline void B::_internal_set_b(const std::string& value) {
  
  _impl_.b_.Set(value, GetArenaForAllocation());
}
inline std::string* B::_internal_mutable_b() {
  
  return _impl_.b_.Mutable(GetArenaForAllocation());
}
inline std::string* B::release_b() {
  // @@protoc_insertion_point(field_release:helloworld.B.b)
  return _impl_.b_.Release();
}
inline void B::set_allocated_b(std::string* b) {
  if (b != nullptr) {
    
  } else {
    
  }
  _impl_.b_.SetAllocated(b, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.b_.IsDefault()) {
    _impl_.b_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:helloworld.B.b)
}

// -------------------------------------------------------------------

// CRPCProtocol_Inner

// string method = 1;
inline void CRPCProtocol_Inner::clear_method() {
  _impl_.method_.ClearToEmpty();
}
inline const std::string& CRPCProtocol_Inner::method() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.Inner.method)
  return _internal_method();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CRPCProtocol_Inner::set_method(ArgT0&& arg0, ArgT... args) {
 
 _impl_.method_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.Inner.method)
}
inline std::string* CRPCProtocol_Inner::mutable_method() {
  std::string* _s = _internal_mutable_method();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.Inner.method)
  return _s;
}
inline const std::string& CRPCProtocol_Inner::_internal_method() const {
  return _impl_.method_.Get();
}
inline void CRPCProtocol_Inner::_internal_set_method(const std::string& value) {
  
  _impl_.method_.Set(value, GetArenaForAllocation());
}
inline std::string* CRPCProtocol_Inner::_internal_mutable_method() {
  
  return _impl_.method_.Mutable(GetArenaForAllocation());
}
inline std::string* CRPCProtocol_Inner::release_method() {
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.Inner.method)
  return _impl_.method_.Release();
}
inline void CRPCProtocol_Inner::set_allocated_method(std::string* method) {
  if (method != nullptr) {
    
  } else {
    
  }
  _impl_.method_.SetAllocated(method, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.method_.IsDefault()) {
    _impl_.method_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.Inner.method)
}

// uint64 callback = 2;
inline void CRPCProtocol_Inner::clear_callback() {
  _impl_.callback_ = uint64_t{0u};
}
inline uint64_t CRPCProtocol_Inner::_internal_callback() const {
  return _impl_.callback_;
}
inline uint64_t CRPCProtocol_Inner::callback() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.Inner.callback)
  return _internal_callback();
}
inline void CRPCProtocol_Inner::_internal_set_callback(uint64_t value) {
  
  _impl_.callback_ = value;
}
inline void CRPCProtocol_Inner::set_callback(uint64_t value) {
  _internal_set_callback(value);
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.Inner.callback)
}

// uint64 callbackArgs = 3;
inline void CRPCProtocol_Inner::clear_callbackargs() {
  _impl_.callbackargs_ = uint64_t{0u};
}
inline uint64_t CRPCProtocol_Inner::_internal_callbackargs() const {
  return _impl_.callbackargs_;
}
inline uint64_t CRPCProtocol_Inner::callbackargs() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.Inner.callbackArgs)
  return _internal_callbackargs();
}
inline void CRPCProtocol_Inner::_internal_set_callbackargs(uint64_t value) {
  
  _impl_.callbackargs_ = value;
}
inline void CRPCProtocol_Inner::set_callbackargs(uint64_t value) {
  _internal_set_callbackargs(value);
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.Inner.callbackArgs)
}

// -------------------------------------------------------------------

// CRPCProtocol

// string method = 1;
inline void CRPCProtocol::clear_method() {
  _impl_.method_.ClearToEmpty();
}
inline const std::string& CRPCProtocol::method() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.method)
  return _internal_method();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CRPCProtocol::set_method(ArgT0&& arg0, ArgT... args) {
 
 _impl_.method_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.method)
}
inline std::string* CRPCProtocol::mutable_method() {
  std::string* _s = _internal_mutable_method();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.method)
  return _s;
}
inline const std::string& CRPCProtocol::_internal_method() const {
  return _impl_.method_.Get();
}
inline void CRPCProtocol::_internal_set_method(const std::string& value) {
  
  _impl_.method_.Set(value, GetArenaForAllocation());
}
inline std::string* CRPCProtocol::_internal_mutable_method() {
  
  return _impl_.method_.Mutable(GetArenaForAllocation());
}
inline std::string* CRPCProtocol::release_method() {
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.method)
  return _impl_.method_.Release();
}
inline void CRPCProtocol::set_allocated_method(std::string* method) {
  if (method != nullptr) {
    
  } else {
    
  }
  _impl_.method_.SetAllocated(method, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.method_.IsDefault()) {
    _impl_.method_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.method)
}

// uint64 funHandle = 2;
inline void CRPCProtocol::clear_funhandle() {
  _impl_.funhandle_ = uint64_t{0u};
}
inline uint64_t CRPCProtocol::_internal_funhandle() const {
  return _impl_.funhandle_;
}
inline uint64_t CRPCProtocol::funhandle() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.funHandle)
  return _internal_funhandle();
}
inline void CRPCProtocol::_internal_set_funhandle(uint64_t value) {
  
  _impl_.funhandle_ = value;
}
inline void CRPCProtocol::set_funhandle(uint64_t value) {
  _internal_set_funhandle(value);
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.funHandle)
}

// bytes request = 3;
inline void CRPCProtocol::clear_request() {
  _impl_.request_.ClearToEmpty();
}
inline const std::string& CRPCProtocol::request() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.request)
  return _internal_request();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CRPCProtocol::set_request(ArgT0&& arg0, ArgT... args) {
 
 _impl_.request_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.request)
}
inline std::string* CRPCProtocol::mutable_request() {
  std::string* _s = _internal_mutable_request();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.request)
  return _s;
}
inline const std::string& CRPCProtocol::_internal_request() const {
  return _impl_.request_.Get();
}
inline void CRPCProtocol::_internal_set_request(const std::string& value) {
  
  _impl_.request_.Set(value, GetArenaForAllocation());
}
inline std::string* CRPCProtocol::_internal_mutable_request() {
  
  return _impl_.request_.Mutable(GetArenaForAllocation());
}
inline std::string* CRPCProtocol::release_request() {
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.request)
  return _impl_.request_.Release();
}
inline void CRPCProtocol::set_allocated_request(std::string* request) {
  if (request != nullptr) {
    
  } else {
    
  }
  _impl_.request_.SetAllocated(request, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.request_.IsDefault()) {
    _impl_.request_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.request)
}

// bytes response = 4;
inline void CRPCProtocol::clear_response() {
  _impl_.response_.ClearToEmpty();
}
inline const std::string& CRPCProtocol::response() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.response)
  return _internal_response();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CRPCProtocol::set_response(ArgT0&& arg0, ArgT... args) {
 
 _impl_.response_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.response)
}
inline std::string* CRPCProtocol::mutable_response() {
  std::string* _s = _internal_mutable_response();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.response)
  return _s;
}
inline const std::string& CRPCProtocol::_internal_response() const {
  return _impl_.response_.Get();
}
inline void CRPCProtocol::_internal_set_response(const std::string& value) {
  
  _impl_.response_.Set(value, GetArenaForAllocation());
}
inline std::string* CRPCProtocol::_internal_mutable_response() {
  
  return _impl_.response_.Mutable(GetArenaForAllocation());
}
inline std::string* CRPCProtocol::release_response() {
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.response)
  return _impl_.response_.Release();
}
inline void CRPCProtocol::set_allocated_response(std::string* response) {
  if (response != nullptr) {
    
  } else {
    
  }
  _impl_.response_.SetAllocated(response, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.response_.IsDefault()) {
    _impl_.response_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.response)
}

// .helloworld.CRPCProtocol.ErrorCode code = 10;
inline void CRPCProtocol::clear_code() {
  _impl_.code_ = 0;
}
inline ::helloworld::CRPCProtocol_ErrorCode CRPCProtocol::_internal_code() const {
  return static_cast< ::helloworld::CRPCProtocol_ErrorCode >(_impl_.code_);
}
inline ::helloworld::CRPCProtocol_ErrorCode CRPCProtocol::code() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.code)
  return _internal_code();
}
inline void CRPCProtocol::_internal_set_code(::helloworld::CRPCProtocol_ErrorCode value) {
  
  _impl_.code_ = value;
}
inline void CRPCProtocol::set_code(::helloworld::CRPCProtocol_ErrorCode value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.code)
}

// string msg = 11;
inline void CRPCProtocol::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& CRPCProtocol::msg() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CRPCProtocol::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:helloworld.CRPCProtocol.msg)
}
inline std::string* CRPCProtocol::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.msg)
  return _s;
}
inline const std::string& CRPCProtocol::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void CRPCProtocol::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* CRPCProtocol::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* CRPCProtocol::release_msg() {
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.msg)
  return _impl_.msg_.Release();
}
inline void CRPCProtocol::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.msg)
}

// .helloworld.CRPCProtocol.Inner inner = 100;
inline bool CRPCProtocol::_internal_has_inner() const {
  return this != internal_default_instance() && _impl_.inner_ != nullptr;
}
inline bool CRPCProtocol::has_inner() const {
  return _internal_has_inner();
}
inline void CRPCProtocol::clear_inner() {
  if (GetArenaForAllocation() == nullptr && _impl_.inner_ != nullptr) {
    delete _impl_.inner_;
  }
  _impl_.inner_ = nullptr;
}
inline const ::helloworld::CRPCProtocol_Inner& CRPCProtocol::_internal_inner() const {
  const ::helloworld::CRPCProtocol_Inner* p = _impl_.inner_;
  return p != nullptr ? *p : reinterpret_cast<const ::helloworld::CRPCProtocol_Inner&>(
      ::helloworld::_CRPCProtocol_Inner_default_instance_);
}
inline const ::helloworld::CRPCProtocol_Inner& CRPCProtocol::inner() const {
  // @@protoc_insertion_point(field_get:helloworld.CRPCProtocol.inner)
  return _internal_inner();
}
inline void CRPCProtocol::unsafe_arena_set_allocated_inner(
    ::helloworld::CRPCProtocol_Inner* inner) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.inner_);
  }
  _impl_.inner_ = inner;
  if (inner) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helloworld.CRPCProtocol.inner)
}
inline ::helloworld::CRPCProtocol_Inner* CRPCProtocol::release_inner() {
  
  ::helloworld::CRPCProtocol_Inner* temp = _impl_.inner_;
  _impl_.inner_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::helloworld::CRPCProtocol_Inner* CRPCProtocol::unsafe_arena_release_inner() {
  // @@protoc_insertion_point(field_release:helloworld.CRPCProtocol.inner)
  
  ::helloworld::CRPCProtocol_Inner* temp = _impl_.inner_;
  _impl_.inner_ = nullptr;
  return temp;
}
inline ::helloworld::CRPCProtocol_Inner* CRPCProtocol::_internal_mutable_inner() {
  
  if (_impl_.inner_ == nullptr) {
    auto* p = CreateMaybeMessage<::helloworld::CRPCProtocol_Inner>(GetArenaForAllocation());
    _impl_.inner_ = p;
  }
  return _impl_.inner_;
}
inline ::helloworld::CRPCProtocol_Inner* CRPCProtocol::mutable_inner() {
  ::helloworld::CRPCProtocol_Inner* _msg = _internal_mutable_inner();
  // @@protoc_insertion_point(field_mutable:helloworld.CRPCProtocol.inner)
  return _msg;
}
inline void CRPCProtocol::set_allocated_inner(::helloworld::CRPCProtocol_Inner* inner) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.inner_;
  }
  if (inner) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(inner);
    if (message_arena != submessage_arena) {
      inner = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, inner, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.inner_ = inner;
  // @@protoc_insertion_point(field_set_allocated:helloworld.CRPCProtocol.inner)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace helloworld

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::helloworld::CRPCProtocol_ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::helloworld::CRPCProtocol_ErrorCode>() {
  return ::helloworld::CRPCProtocol_ErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_helloworld_2eproto
