// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.5
// source: crpc.proto

package call

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CRPCProtocol_ErrorCode int32

const (
	CRPCProtocol_Unknown         CRPCProtocol_ErrorCode = 0
	CRPCProtocol_OK              CRPCProtocol_ErrorCode = 1
	CRPCProtocol_Fail            CRPCProtocol_ErrorCode = 2
	CRPCProtocol_NotInit         CRPCProtocol_ErrorCode = 3
	CRPCProtocol_NoResponse      CRPCProtocol_ErrorCode = 4
	CRPCProtocol_Unimplemented   CRPCProtocol_ErrorCode = 5
	CRPCProtocol_InvalidArgument CRPCProtocol_ErrorCode = 6
)

// Enum value maps for CRPCProtocol_ErrorCode.
var (
	CRPCProtocol_ErrorCode_name = map[int32]string{
		0: "Unknown",
		1: "OK",
		2: "Fail",
		3: "NotInit",
		4: "NoResponse",
		5: "Unimplemented",
		6: "InvalidArgument",
	}
	CRPCProtocol_ErrorCode_value = map[string]int32{
		"Unknown":         0,
		"OK":              1,
		"Fail":            2,
		"NotInit":         3,
		"NoResponse":      4,
		"Unimplemented":   5,
		"InvalidArgument": 6,
	}
)

func (x CRPCProtocol_ErrorCode) Enum() *CRPCProtocol_ErrorCode {
	p := new(CRPCProtocol_ErrorCode)
	*p = x
	return p
}

func (x CRPCProtocol_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CRPCProtocol_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_crpc_proto_enumTypes[0].Descriptor()
}

func (CRPCProtocol_ErrorCode) Type() protoreflect.EnumType {
	return &file_crpc_proto_enumTypes[0]
}

func (x CRPCProtocol_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CRPCProtocol_ErrorCode.Descriptor instead.
func (CRPCProtocol_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_crpc_proto_rawDescGZIP(), []int{0, 0}
}

type CRPCProtocol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`        // 方法
	FunHandle     uint64                 `protobuf:"varint,2,opt,name=funHandle,proto3" json:"funHandle,omitempty"` // 回调函数
	Request       []byte                 `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`      // 请求
	Response      []byte                 `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`    // 回复
	Code          CRPCProtocol_ErrorCode `protobuf:"varint,10,opt,name=code,proto3,enum=call.CRPCProtocol_ErrorCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,11,opt,name=msg,proto3" json:"msg,omitempty"`
	Inner         *CRPCProtocol_Inner    `protobuf:"bytes,100,opt,name=inner,proto3" json:"inner,omitempty"` // 内部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRPCProtocol) Reset() {
	*x = CRPCProtocol{}
	mi := &file_crpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRPCProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRPCProtocol) ProtoMessage() {}

func (x *CRPCProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_crpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRPCProtocol.ProtoReflect.Descriptor instead.
func (*CRPCProtocol) Descriptor() ([]byte, []int) {
	return file_crpc_proto_rawDescGZIP(), []int{0}
}

func (x *CRPCProtocol) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CRPCProtocol) GetFunHandle() uint64 {
	if x != nil {
		return x.FunHandle
	}
	return 0
}

func (x *CRPCProtocol) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CRPCProtocol) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CRPCProtocol) GetCode() CRPCProtocol_ErrorCode {
	if x != nil {
		return x.Code
	}
	return CRPCProtocol_Unknown
}

func (x *CRPCProtocol) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CRPCProtocol) GetInner() *CRPCProtocol_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

type CRPCProtocol_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Callback      uint64                 `protobuf:"varint,2,opt,name=callback,proto3" json:"callback,omitempty"`
	CallbackArgs  uint64                 `protobuf:"varint,3,opt,name=callbackArgs,proto3" json:"callbackArgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRPCProtocol_Inner) Reset() {
	*x = CRPCProtocol_Inner{}
	mi := &file_crpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRPCProtocol_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRPCProtocol_Inner) ProtoMessage() {}

func (x *CRPCProtocol_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_crpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRPCProtocol_Inner.ProtoReflect.Descriptor instead.
func (*CRPCProtocol_Inner) Descriptor() ([]byte, []int) {
	return file_crpc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CRPCProtocol_Inner) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CRPCProtocol_Inner) GetCallback() uint64 {
	if x != nil {
		return x.Callback
	}
	return 0
}

func (x *CRPCProtocol_Inner) GetCallbackArgs() uint64 {
	if x != nil {
		return x.CallbackArgs
	}
	return 0
}

var File_crpc_proto protoreflect.FileDescriptor

var file_crpc_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x63, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x61,
	0x6c, 0x6c, 0x22, 0xc0, 0x03, 0x0a, 0x0c, 0x43, 0x52, 0x50, 0x43, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x75, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x66, 0x75, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x30, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x52, 0x50, 0x43, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x64, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x52, 0x50, 0x43, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x05, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x1a, 0x5f, 0x0a, 0x05, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x72, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x41, 0x72, 0x67, 0x73, 0x22, 0x6f, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x10, 0x03, 0x12, 0x0e, 0x0a,
	0x0a, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x04, 0x12, 0x11, 0x0a,
	0x0d, 0x55, 0x6e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x10, 0x05,
	0x12, 0x13, 0x0a, 0x0f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x41, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x10, 0x06, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x32, 0x35, 0x32, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x63, 0x72, 0x70, 0x63, 0x2f, 0x63,
	0x72, 0x70, 0x63, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_crpc_proto_rawDescOnce sync.Once
	file_crpc_proto_rawDescData []byte
)

func file_crpc_proto_rawDescGZIP() []byte {
	file_crpc_proto_rawDescOnce.Do(func() {
		file_crpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crpc_proto_rawDesc), len(file_crpc_proto_rawDesc)))
	})
	return file_crpc_proto_rawDescData
}

var file_crpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_crpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_crpc_proto_goTypes = []any{
	(CRPCProtocol_ErrorCode)(0), // 0: call.CRPCProtocol.ErrorCode
	(*CRPCProtocol)(nil),        // 1: call.CRPCProtocol
	(*CRPCProtocol_Inner)(nil),  // 2: call.CRPCProtocol.Inner
}
var file_crpc_proto_depIdxs = []int32{
	0, // 0: call.CRPCProtocol.code:type_name -> call.CRPCProtocol.ErrorCode
	2, // 1: call.CRPCProtocol.inner:type_name -> call.CRPCProtocol.Inner
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_crpc_proto_init() }
func file_crpc_proto_init() {
	if File_crpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crpc_proto_rawDesc), len(file_crpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crpc_proto_goTypes,
		DependencyIndexes: file_crpc_proto_depIdxs,
		EnumInfos:         file_crpc_proto_enumTypes,
		MessageInfos:      file_crpc_proto_msgTypes,
	}.Build()
	File_crpc_proto = out.File
	file_crpc_proto_goTypes = nil
	file_crpc_proto_depIdxs = nil
}
